server:
  port: 8085

spring:
  datasource:
    username: root
    password: dqbjh71ldqbjh71l
    url: jdbc:mysql://localhost:3306/task?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
